### ISSUE TITLE
<Icon> is not a valid SSR component.

### ISSUE THREAD

**Issue by AdrianNigro** [JustinVoitel/svelte-hero-icons#10]
The error:

``` html
500
<Icon> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
Error: <Icon> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Proxy.validate_component (/home/adn/dev/svelte-icon/node_modules/svelte/internal/index.js:1661:15)
    at index.svelte:6:11
    at Object.$$render (/home/adn/dev/svelte-icon/node_modules/svelte/internal/index.js:1684:22)
    at Object.default (root.svelte:38:46)
    at eval (/.svelte-kit/dev/components/layout.svelte:8:41)
    at Object.$$render (/home/adn/dev/svelte-icon/node_modules/svelte/internal/index.js:1684:22)
    at root.svelte:36:44
    at $$render (/home/adn/dev/svelte-icon/node_modules/svelte/internal/index.js:1684:22)
    at Object.render (/home/adn/dev/svelte-icon/node_modules/svelte/internal/index.js:1692:26)
    at render_response (file:///home/adn/dev/svelte-icon/node_modules/@sveltejs/kit/dist/ssr.js:561:28)

```

To reproduce it:
1) start a new sveltekit project `npm init svelte@next my-app`
2) install svelte-hero-icons `npm i svelte-hero-icons`
3) use Icon componente
``` html
<script>
	import Icon, {Users} from 'svelte-hero-icons';
</script>
<Icon src={Users} />
```

Config
package.json
``` json
{
  "name": "svelte-icon",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/kit": "next",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.1",
    "prettier": "^2.4.1",
    "prettier-plugin-svelte": "^2.4.0",
    "svelte": "^3.42.6",
    "svelte-hero-icons": "^3.0.0"
  },
  "type": "module"
}
```

**Comment by JustinVoitel** [comment]
Can you try it again using 3.1.0 ?
Don't forget to add this to your svelte.config.js:
```js
vite: {
  ssr: {
    noExternal: ["svelte-hero-icons"],
  }
}
```

**Comment by wearefyi** [comment]
Icon needs to be defined inside the brackets.

**Comment by JustinVoitel** [comment]
> Icon needs to be defined inside the brackets.

Haven't seen that in the first place :D
so either import the component via the export map:
```js
import {Icon, Annotation} from "svelte-hero-icons"
```
Or import it as a standalone import:

**Comment by JustinVoitel** [comment]
Forget my comment before!
In [4.0.1](https://github.com/JustinVoitel/svelte-hero-icons/releases/tag/v4.0.1) it is now only possible to import the Icon via a map:
```js
import {Icon} form "svelte-hero-icons"
```
This might be a Breaking change for some, but easily refactorable!
